import Link from 'next/link'
import Footer from '@/components/Footer'
import Navigation from '@/components/Navigation'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Use & Legal Disclaimer — LMIA Check',
  description:
    'Terms of Use and Legal Disclaimer for lmiacheck.ca, a neutral aggregator of public Government of Canada Temporary Foreign Worker Program data.',
  alternates: { canonical: 'https://lmiacheck.ca/terms' },
  robots: { index: true, follow: true },
}

const EFFECTIVE_DATE = 'May 30, 2026'

function H2({ children }: { children: React.ReactNode }) {
  return <h2 className="text-lg font-bold text-gray-900 mt-8 mb-3">{children}</h2>
}

function P({ children }: { children: React.ReactNode }) {
  return <p className="text-[15px] text-gray-600 leading-relaxed mb-3">{children}</p>
}

export default function TermsPage() {
  return (
    <div className="flex flex-col min-h-screen bg-gray-50">
      <Navigation />
      <main className="flex-1 max-w-2xl mx-auto w-full px-4 py-8">
        <h1 className="text-2xl font-bold text-gray-900 mb-1">Terms of Use &amp; Legal Disclaimer</h1>
        <p className="text-xs text-gray-400 mb-6">Effective {EFFECTIVE_DATE}</p>

        <div className="p-4 bg-amber-50 rounded-2xl mb-6">
          <p className="text-sm text-amber-900 leading-relaxed">
            <span className="font-semibold">Read this first.</span> lmiacheck.ca (the
            &ldquo;Site&rdquo;) is a free, automated tool that <span className="font-semibold">reproduces
            public Government of Canada records</span>. It is not affiliated with, endorsed by, or
            operated by the Government of Canada. It is an information service, not legal, immigration,
            or financial advice.
          </p>
        </div>

        <H2>1. Acceptance of these Terms</H2>
        <P>
          By accessing or using the Site you agree to be bound by these Terms of Use and the Legal
          Disclaimer below. If you do not agree, do not use the Site. We may update these Terms at any
          time; continued use after a change constitutes acceptance of the revised Terms.
        </P>

        <H2>2. Nature of the service — a neutral data host</H2>
        <P>
          The Site aggregates and displays information drawn from publicly available datasets published
          by Employment and Social Development Canada (ESDC) under the Temporary Foreign Worker Program
          (TFWP), including the Positive Labour Market Impact Assessment (LMIA) Employers List and the
          list of employers found non-compliant. We act solely as a neutral conduit and search interface
          for this third-party public data. We do not author, originate, investigate, verify, edit,
          endorse, or adopt the underlying records, and we do not make any independent judgment,
          allegation, or representation about any employer.
        </P>
        <P>
          Any verdict, label, summary, category, or wording shown on the Site (including words such as
          &ldquo;Verified&rdquo;, &ldquo;Caution&rdquo;, &ldquo;Penalised&rdquo;, &ldquo;Banned&rdquo;,
          or &ldquo;Not found&rdquo;) is an automated, good-faith characterisation of the underlying
          government record as published, generated by software without human review. It is not a
          statement of fact made by us about any employer.
        </P>

        <H2>3. No warranty — data provided &ldquo;as is&rdquo;</H2>
        <P>
          The data and all content on the Site are provided <span className="font-semibold">&ldquo;as
          is&rdquo; and &ldquo;as available&rdquo;</span>, without warranties or representations of any
          kind, whether express, implied, statutory, or otherwise. To the fullest extent permitted by
          law, we expressly disclaim all warranties, including any implied warranties of accuracy,
          completeness, currency, reliability, merchantability, fitness for a particular purpose, title,
          and non-infringement.
        </P>
        <P>
          We do <span className="font-semibold">not</span> guarantee that the information is accurate,
          complete, current, or free of error. Government source data may be delayed, revised, withdrawn,
          corrected, mis-keyed, or superseded at any time without notice. Records may be matched to the
          wrong entity, may omit later remediation, appeals, payments, or reinstatements, and may not
          reflect an employer&rsquo;s present status. The Site may be unavailable, interrupted, or
          contain technical errors. You are responsible for independently verifying any information
          before relying on it.
        </P>

        <H2>4. Not advice — verify independently</H2>
        <P>
          Nothing on the Site constitutes legal, immigration, employment, financial, or other
          professional advice, and no professional relationship is created by your use of it. Decisions
          about a job offer, employer, recruiter, or immigration matter should be made only after
          confirming the information directly with the employer and with the Government of Canada, and
          after seeking advice from a licensed Regulated Canadian Immigration Consultant (RCIC) or a
          lawyer. Always confirm any status directly with Service Canada and the official Government of
          Canada sources linked on the Site.
        </P>

        <H2>5. Limitation of liability</H2>
        <P>
          To the fullest extent permitted by applicable law, in no event will the Site, its operators,
          owners, contributors, or suppliers be liable for any direct, indirect, incidental, special,
          consequential, exemplary, or punitive damages, or for any loss of profits, opportunities,
          data, reputation, or goodwill, arising out of or related to your access to or use of (or
          inability to use) the Site or its content, whether based in contract, tort (including
          negligence), statute, or any other legal theory, and whether or not we have been advised of
          the possibility of such damages. Your sole and exclusive remedy is to stop using the Site.
        </P>

        <H2>6. Indemnity</H2>
        <P>
          You agree to indemnify and hold harmless the Site and its operators from and against any
          claims, demands, losses, liabilities, and expenses (including reasonable legal fees) arising
          out of your use of the Site or your breach of these Terms.
        </P>

        <H2>7. Notice and correction for employers</H2>
        <P>
          We do not control the contents of the underlying government datasets and cannot alter the
          official record. If you are an employer and believe a government record about you is incorrect
          or out of date, you must seek correction at the source through Employment and Social
          Development Canada / Service Canada. Where the official source record is updated, the change
          will be reflected on the Site after the next data refresh.
        </P>
        <P>
          If you believe content on the Site does not faithfully reproduce the corresponding public
          government record, contact us at{' '}
          <a className="text-blue-600 underline" href="mailto:legal@lmiacheck.ca">
            legal@lmiacheck.ca
          </a>{' '}
          and we will review the reproduction in good faith.
        </P>

        <H2>8. Acceptable use</H2>
        <P>
          You may not use the Site to harass any person, to scrape or bulk-extract data in a manner that
          burdens our infrastructure, to misrepresent the data, or for any unlawful purpose. The Site and
          its original design, text, and software are protected by copyright; the underlying government
          data is governed by the licence described in our footer attribution.
        </P>

        <H2>9. Governing law</H2>
        <P>
          These Terms are governed by the laws of the Province of Ontario and the federal laws of Canada
          applicable therein, without regard to conflict-of-laws principles. You agree to the exclusive
          jurisdiction of the courts located in Ontario for any dispute arising from these Terms or the
          Site.
        </P>

        <H2>10. Contact</H2>
        <P>
          Questions about these Terms:{' '}
          <a className="text-blue-600 underline" href="mailto:legal@lmiacheck.ca">
            legal@lmiacheck.ca
          </a>
          . See also our{' '}
          <Link className="text-blue-600 underline" href="/privacy">
            Privacy Policy
          </Link>
          .
        </P>

        <p className="text-xs text-gray-400 leading-relaxed mt-10 border-t border-gray-200 pt-5">
          This document is a general template and not a substitute for advice from a licensed lawyer.
          Have it reviewed by Ontario/Canadian counsel before relying on it.
        </p>
      </main>
      <Footer />
    </div>
  )
}
